name: sample html export- docker
on:
  push:
    branch:
      - master
    
jobs:
  push_to_registry:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: dhammuu/gitactions
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
